name: Pylint

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analyzing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
    - name: Run unit tests
      run:
        echo This is a test
        python -V
        #python unit_tests.py
#    - name: Build Docker image
#    - name: Test Docker image
#    - name: Deploy Docker image
