name: shell_push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo 
      uses: actions/checkout@v2
        
    - name: Download build script
      run: wget https://raw.githubusercontent.com/stewart-lab/fast_km/master/actions/build_workflow.sh
      
    - name: Change permissions so that build script is executable
      run: chmod +x ./build_workflow.sh
      
    - name: Run build script
      run:  ./build_workflow.sh
      
    - name: Download deploy script
      run: wget https://raw.githubusercontent.com/stewart-lab/fast_km/master/actions/deploy_workflow.sh
      
    - name: Change permissions so that deploy script is executable
      run: chmod +x ./deploy_workflow.sh
      
    - name: Run deploy script
      run:  ./deploy_workflow.sh
