name: shell_build

on: [pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      
    - name: Download build script
      run: wget https://raw.githubusercontent.com/stewart-lab/fast_km/master/actions/build_workflow.sh
    
    - name: Change build script permissions so that it is executable
      run: chmod +x ./build_workflow.sh
      
    - name: Log in to Dockerhub
      run: docker login -u ${{secrets.HUB_ACCOUNT}} -p ${{secrets.HUB_TOKEN}}
      
    - name: Run build script
      run: ./build_workflow.sh
